- name: Update and maintain system
  hosts: homelab
  become: true
  gather_facts: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      tags: [update]

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      register: apt_upgrade
      tags: [update]

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      tags: [update]

    - name: Display reboot status
      ansible.builtin.debug:
        msg: "Reboot is required!"
      when: reboot_required_file.stat.exists
      tags: [update]

    - name: List changed packages
      ansible.builtin.debug:
        var: apt_upgrade.stdout_lines
      when: apt_upgrade.changed
      tags: [update]
